language: php

addons:
  chrome: stable
  apt:
    packages:
      - nginx

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1 RUN_E2E=1
  - php: 7.1
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  allow_failures:
  - env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  - php: 7.3

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^release\//